package com.hbs.tracking.enums;

public enum TrackingEventType {
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_RESUMED,
    SUBSCRIPTION_DELETED,

    MESSAGE_INGEST_REQUESTED,
    MESSAGE_INGEST_ACCEPTED,
    MESSAGE_FANOUT_STARTED,
    MESSAGE_PUBLISHED_TO_KAFKA,
    MESSAGE_DELIVERED_TO_GATEWAY,
    MESSAGE_PUSHED_TO_SSE,
    MESSAGE_REDELIVERED,
    MESSAGE_DELIVERY_FAILED
}
